language: python
matrix:
    include:
        - python: 3.3
          dist: trusty
          sudo: false
        - python: 3.4
          dist: trusty
          sudo: false
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
# command to run tests
script:
  - PYTHONPATH=src python3 -m unittest discover tests/ -v
